name: Run Test

on:
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - 'main'

jobs:
    Run-Test:
        runs-on: ubuntu-latest

        steps:
            - name: Hello World
              run: echo "Hello World"

            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                node-version: 21.7.3

            - name: Install Dependencies
              run: npm ci

            - name: Run Tests
              run: npm run test